config/routes.rb
Rails.application.routes.draw do
  post 'copy/create'
  post 'formulas/log'
  get 'formulas/set_history'
  delete 'formulas/delete_history'
  put 'formulas/update_daily_usage'

  root 'welcome#index'

  get    'dashboard' => 'dashboard#index'
  get    'login'   => 'welcome#index'
  delete 'logout'  => 'sessions#destroy'
  get    'signup' => 'users#new'

  resources :ingredients
  resources :formulas
  resources :premixes
  resources :nutrients
  resources :users do
    put 'lock'
    put 'activate'
  end
  resource :sessions, only: [:new, :create, :destroy]
  resources :ingredient_usages, only: [:index]

end

app/controllers/dashboard_controller.rb
class DashboardController < ApplicationController

  def index
    @formulas_count = current_user.formulas.count
    @ingredients_count = current_user.ingredients.count
    @nutrients_count = current_user.nutrients.count
  end

end

app/views/dashboard/index.html.haml
= render_flash

.container
  %h1
    %strong
      Hello,
      = current_user.name
.container
  .row
    .col-sm-3.bg-success
      %h2
        = link_to @formulas_count.to_s + " Formulas", formulas_path
        = link_to "New Formula", new_formula_path, class: 'btn btn-success'
      %p Formula is the mixture of ingredients that form a diet for animals.
    .col-sm-3.bg-danger
      %h3
        = link_to @ingredients_count.to_s + " Ingredients", ingredients_path
        = link_to "New Ingredient", new_ingredient_path, class: 'btn btn-danger'
      %p An ingredient is a substance that forms part of a formula (in a general sense). For example, in cooking, recipes specify which ingredients are used to prepare a specific dish.
    .col-sm-3.bg-info
      %h3
        = link_to @nutrients_count.to_s + " Nutrients", nutrients_path
        = link_to "New Nutrient", new_nutrient_path, class: 'btn btn-info'
      %p Nutrients are the nutritious components in foods that an organism utilizes to survive and grow.

%hr
  %footer
    %strong
      The MIT License (MIT)
    %p Copyright (c) 2014 Tan Kwang How
    %p
      Permission is hereby granted, free of charge, to any person obtaining a copy
      of this software and associated documentation files (the "Software"), to deal
      in the Software without restriction, including without limitation the rights
      to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
      copies of the Software, and to permit persons to whom the Software is
      furnished to do so, subject to the following conditions:
    %p
      The above copyright notice and this permission notice shall be included in
      all copies or substantial portions of the Software.
    %p
      THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
      IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
      FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
      AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
      LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
      OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN
      THE SOFTWARE.

      %p= mail_to 'leastcostfeed@gmail.com'