config/routes.rb
Rails.application.routes.draw do
  post 'copy/create'
  post 'formulas/log'
  get 'formulas/set_history'
  delete 'formulas/delete_history'
  put 'formulas/update_daily_usage'

  root 'welcome#index'

  get    'dashboard' => 'dashboard#index'
  get    'login'   => 'welcome#index'
  delete 'logout'  => 'sessions#destroy'
  get    'signup' => 'users#new'

  resources :ingredients
  resources :formulas
  resources :premixes
  resources :nutrients
  resources :users do
    put 'lock'
    put 'activate'
  end
  resource :sessions, only: [:new, :create, :destroy]
  resources :ingredient_usages, only: [:index]

end

app/models/user.rb
require 'csv'

class User < ActiveRecord::Base
  has_secure_password
  include SentientUser
  validates :username, uniqueness: true
  validates :name, :username, :time_zone, :country, :weight_unit, :status, :email, presence: true
  has_many :formulas, dependent: :destroy
  has_many :ingredients, dependent: :destroy
  has_many :nutrients, dependent: :destroy
  has_many :premixes

  after_create :add_sample_nutrients_and_ingredients

  def self.find_users terms=nil, page=1
    if terms.blank?
      User.all.page(page).order(:name)
    else
      User.where("username || name || email || status ilike ?", "%#{terms}%").page(page).order(:name)
    end
  end

  def logged_in
    self.last_login_at = DateTime.now
    self.save
  end

private

  def add_sample_nutrients_and_ingredients
    if Rails.env != 'test'
      seed_sample_nutrients
      seed_sample_ingredients
      seed_sample_ingredient_nutrients
      seed_sample_formula
    end
  end

  def seed_sample_formula
    f = Formula.create! name: 'Sample', batch_size: 1000, user_id: self.id
    fi = [[true, "Limestone",            0.092912,  185.824,  0       ],
          [true, "Wheat Bran",           0.082865,  165.73,   0       ],
          [true, "Palm Oil",             0.075485,  150.97,   0       ],
          [true, "MDCP21",               0.011939,  23.878,   0       ],
          [true, "DL-Methionine 99",     0.002162,  4.324,    0       ],
          [true, "Sodium Bicab",         0.000919,  1.838,    0       ],
          [true, "L-Threonine",          0,         0,        9.924164],
          [true, "Rice Bran",            0,         0,        0.152984],
          [true, "SS Soyabean Meal DHP",  0.369659,  739.318,  0       ],
          [true, "Common Salt",          0.00284,   5.68,     0       ],
          [true, "L-Lysine HCl",         0,         0,        8.254647]]

    fn = [[true, "Calcium",               3.9,  4.1, 3.9      ],
          [true, "Chlorine",              0.17, 0.2, 0.2      ],
          [true, "Choline",               1.4,  nil, 1.4      ],
          [true, "Crude Fiber",           3,    5.5, 3        ],
          [true, "Crude Protein",         18,   nil, 21.199256],
          [true, "Isoleucine",            0.7,  nil, 0.873824 ],
          [true, "Linoleic Acid",         1.8,  nil, 1.920556 ],
          [true, "Lysine",                0.91, nil, 1.140147 ],
          [true, "Met + Cys",             0.8,  nil, 0.8      ],
          [true, "Metab. Energy", 2.85, nil, 2.85     ],
          [true, "Methionine",            0.46, nil, 0.50734  ],
          [true, "Sodium",                0.17, nil, 0.17     ],
          [true, "Threonine",             0.66, nil, 0.736926 ],
          [true, "Tryptophan",            0.21, nil, 0.265001 ],
          [true, "Valine",                0.78, nil, 0.954362 ]]

    fi.each do |t|
      i = Ingredient.find_by_name_and_user_id t[1], self.id
      FormulaIngredient.create! formula_id: f.id, ingredient_id: i.id, actual: t[2], weight: t[3], shadow: t[4], use: t[0]
    end

    fn.each do |t|
      n = Nutrient.find_by_name_and_user_id(t[1], self.id)
      FormulaNutrient.create! formula_id: f.id, nutrient_id: n.id, actual: t[4], use: t[0], min: t[2], max: t[3]
    end
  end

  def seed_sample_ingredients
    CSV.foreach(File.expand_path("app/models/sample_data/ingredients.csv"), headers: true, col_sep: ',') do |d|
      Ingredient.create! name: d["Name"], cost: d['Price'], category: 'sample', user_id: self.id
    end
  end

  def seed_sample_nutrients
    CSV.foreach(File.expand_path("app/models/sample_data/nutrients.csv"), headers: true, col_sep: ',') do |d|
      Nutrient.create! name: d["Nutrient"], unit: d['Unit'], category: 'sample', user_id: self.id
    end
  end

  def seed_sample_ingredient_nutrients
    CSV.foreach(File.expand_path("app/models/sample_data/ingredient_compositions.csv"), headers: true, col_sep: ',') do |d|
      i = Ingredient.find_by_name_and_user_id(d['Ingredient'], self.id)
      d.each do |t|
        n = Nutrient.find_by_name_and_user_id(t[0], self.id) if t[0] != "Ingredient"
        IngredientComposition.create! nutrient_id: n.id, ingredient_id: i.id, value: t[1] if t[1] && n && i
      end
    end
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  skip_before_action :login_required, only: [:new, :create]

  def index
    if current_user.is_admin
      @terms = params[:search] ? params[:search][:terms] : nil
      @users = User.find_users(@terms).page(params[:page])
    else
      redirect_to :root, flash: { danger: "Unauthorize access!" }
    end
  end

  def new
    @user = User.new
  end

  def edit
    fetch_user
  end

  def update
    fetch_user
    if @user.update user_params
      flash[:success] = "#{@user.name} Profile updated successfully. Will be reflect next login."
      redirect_to root_path
    else
      flash[:danger] = "Failed to updated User Profile."
      render :edit
    end
  end

  def create
    @user = User.new user_params
    if User.count < 200
      @user.status = 'active'
    else
      @user.status = 'pending'
    end
    if @user.save
      if @user.status == 'active'
        flash[:success] = 'Yeah! Signed up successfully. Please Login.'
      else
        flash[:success] = 'Yeah! Signed up successfully. Pending approval by System Administrator.'
      end
      redirect_to login_path
    else
      flash[:danger] = 'Ooppps! Failed to signup'
      render :new
    end
  end

  def lock
    fetch_user params[:user_id]
    @user.status = 'locked'
    if @user.save
      flash[:warning] = "Locked #{@user.name}"
    else
      flash[:danger] = "Fail to Lock #{@user.name}. #{@user.errors}"
    end
    redirect_to users_path
  end

  def activate
    fetch_user params[:user_id]
    @user.status = 'active'
    if @user.save
      flash[:success] = "Activated #{@user.name}"
    else
      flash[:danger] = "Fail to Activate #{@user.name}. #{@user.errors}"
    end
    redirect_to users_path
  end

  def destroy
    fetch_user
    @user.destroy
    flash[:success] = "User destroyed successfully."
    redirect_to users_path
  end

private

  def fetch_user id=params[:id]
    if id.to_i == current_user.try(:id) || current_user.is_admin
      @user = User.find(id.to_i)
    else
      redirect_to :back, flash: { danger: "Cannot edit other user." }
    end
  end

  def user_params
    if current_user.try(:is_admin) && current_user.id == @user.id
      params.require(:user).permit(:username, :email, :name, :password, :password_confirmation, :country, :time_zone, :weight_unit, :is_admin, :status)
    elsif !current_user.try(:is_admin)
      params.require(:user).permit(:username, :email, :name, :password, :password_confirmation, :country, :time_zone, :weight_unit)
    else
      params.require(:user).permit(:password, :password_confirmation, :status, :is_admin)
    end
  end

end

app/views/users/edit.html.haml
= render_flash
- disable = (@user.id != current_user.id)
= simple_form_for @user, html: { class: 'center form-horizontal well col-sm-5' }, wrapper: :hows_horizontal do |f|
  %legend Edit User Profile
  = f.input :username, autofocus: true, input_html: { disabled: disable }
  = f.input :name, input_html: { disabled: disable }
  = f.input :email, input_html: { disabled: disable }
  = f.input :password
  = f.input :password_confirmation, label: 'Confirmation'
  = f.input :country, input_html: { disabled: disable }
  = f.input :time_zone, input_html: { disabled: disable }
  = f.input :weight_unit, input_html: { disabled: disable }
  - if current_user.is_admin
    = f.input :is_admin
    = f.input :status, collection: ['active', 'pending', 'locked'], include_blank: false
  %div.col-lg-offset-1
    = f.button :submit, 'Save', class: 'btn btn-primary'
    = link_to 'Cancel', session[:return_to] || dashboard_path, class: 'btn btn-success'

app/views/users/index.html.haml
= render_flash
= simple_form_for :search, url: users_path, html: { class: 'form-horizontal', method: :get } do |f|
  = content_tag :div, class: 'col-sm-5' do
    = f.input_field :terms, autofocus: true, value: @terms, placeholder: 'Search Terms...'
  = f.button :submit, 'Search', class: 'btn btn-primary'
%table.table
  %thead
    %tr
      %th Name
      %th Email
      %th Username
      %th Formulas
      %th Last Login
      %th Status
      %th Admin
      %th
  %tbody
    - @users.each do |u|
      %tr
        %td= link_to u.name, edit_user_path(u)
        %td= u.email
        %td= u.username
        %td= u.formulas.count
        %td= time_ago_in_words(u.last_login_at || u.updated_at)
        %td= u.status
        %td= u.is_admin
        %td
          - if u.status != 'active'
            = link_to "Activate", user_activate_path(u), method: :put, class: 'btn btn-info'
          - else
            = link_to "Lock", user_lock_path(u), method: :put, class: 'btn btn-warning'
          - if u.status == 'locked'
            = link_to "Delete", u, method: :delete, data: { confirm: 'Are You Sure!' }, class: 'btn btn-danger'
= paginate @users, params: { search: params[:search] }, theme: 'twitter-bootstrap-3'

app/views/users/new.html.haml
= render_flash
= simple_form_for @user, html: { class: 'center form-horizontal well col-sm-5' }, wrapper: :hows_horizontal do |f|
  %legend User Signup
  = f.input :username, autofocus: true
  = f.input :name
  = f.input :email
  = f.input :password
  = f.input :password_confirmation, label: 'Confirmation'
  = f.input :country
  = f.input :time_zone
  = f.input :weight_unit
  %div.col-lg-offset-1
    = f.button :submit, 'Sign up', class: 'btn btn-primary'
    = link_to 'Already have an account, go back to Login', login_path, class: 'btn btn-success'