config/routes.rb
Rails.application.routes.draw do
  post 'copy/create'
  post 'formulas/log'
  get 'formulas/set_history'
  delete 'formulas/delete_history'
  put 'formulas/update_daily_usage'

  root 'welcome#index'

  get    'dashboard' => 'dashboard#index'
  get    'login'   => 'welcome#index'
  delete 'logout'  => 'sessions#destroy'
  get    'signup' => 'users#new'

  resources :ingredients
  resources :formulas
  resources :premixes
  resources :nutrients
  resources :users do
    put 'lock'
    put 'activate'
  end
  resource :sessions, only: [:new, :create, :destroy]
  resources :ingredient_usages, only: [:index]

end

app/models/formula.rb
class Formula < ActiveRecord::Base
  belongs_to :user
  validates_presence_of :user_id, :name, :batch_size, :cost
  validates_numericality_of :batch_size, greater_than_or_equal_to: 0.0
  validates_numericality_of :cost, greater_than_or_equal_to: 0.0
  validates_numericality_of :usage_per_day, greater_than_or_equal_to: 0.0
  validates_uniqueness_of :name, scope: :user_id

  has_many :formula_ingredients, -> { includes(:ingredient).order("actual desc") }, dependent: :destroy
  has_many :formula_nutrients, -> { includes(:nutrient).order("actual desc") }, dependent: :destroy
  has_many :formula_ingredients_histories, -> { includes(:ingredient).order("actual desc") }, dependent: :destroy

  accepts_nested_attributes_for :formula_ingredients, allow_destroy: true
  accepts_nested_attributes_for :formula_nutrients, allow_destroy: true

  attr_reader :prev_cost, :status

  def formula_code
    name.match(/\((.*)\)/).to_s.gsub("(", '').gsub(")", '').blank? ?
      id : name.match(/\((.*)\)/).to_s.gsub("(", '').gsub(")", '')
  end

  def self.find_formulas terms=nil, page=1
    if terms.blank?
      User.current.formulas.page(page).order(:name)
    else
      User.current.formulas.where("name ilike ?", "%#{terms}%").order(:name).page(page)
    end
  end

  def calculate params=nil
    assign_attributes params if params
    n = User.current ? User.current.username :  random_word
    sol = DietGlpsol.solution_for_formula self, "#{n}_#{self.id}.mod"
    if sol[0]
      set_actual_to_zero
      put_soultion_to_formula sol[1]
    else
      @status = 'Error ' + sol[1]
    end
    count_cost_set_weight
    self.updated_at = DateTime.now
  end

  def savings
    @prev_cost ? self.cost - @prev_cost : 0
  end

  def self.create_like id
    like = Premix.find id
    a = like.dup
    a.name = like.name + " Copy #{DateTime.now.in_time_zone(User.current.time_zone).strftime('%Y%m%d%H%M%S')}"
    like.formula_ingredients.each do |t|
      a.formula_ingredients.build ingredient: t.ingredient, max: t.max, min: t.min, actual: t.actual, shadow: t.shadow, use: t.use
    end
    like.formula_nutrients.each do |t|
      a.formula_nutrients.build nutrient: t.nutrient, max: t.max, min: t.min, actual: t.actual, use: t.use
    end
    like.premix_ingredients.each do |t|
      a.premix_ingredients.build ingredient: t.ingredient, actual_usage: t.actual_usage, premix_usage: t.premix_usage
    end
    a.save!
    a
  end

  def me
    formula_nutrients.select { |t| t.nutrient.name == 'Metab. Energy' }.first.actual.round(2)
  end

  def cp
    formula_nutrients.select { |t| t.nutrient.name == 'Crude Protein' }.first.actual.round(2)
  end

  def log_to_history
    log_datetime = DateTime.now.to_s(:number)
    formula_ingredients.each do |t|
      formula_ingredients_histories.create! ingredient: t.ingredient, actual: t.actual, use: t.use, logged_at: log_datetime
    end
  end

  def set_current_formula_ingredients_from_history logged_at
    clear_formula_ingredients_mix_max
    formula_ingredients_histories.where(logged_at: logged_at, formula: self).each do |t|
      f = formula_ingredients.find { |k| k.ingredient_id == t.ingredient_id } || formula_ingredients.build(ingredient_id: t.ingredient_id)
      f.min = t.actual
      f.max = t.actual if t.actual <= 0.001
      f.actual = t.actual
      f.use  = true
    end
    formula_nutrients.each { |t| t.use = false }
    self.cost = 0
  end

  def delete_history logged_at
    formula_ingredients_histories.where(logged_at: logged_at, formula: self).each { |t| t.destroy }
  end

private

  def clear_formula_ingredients_mix_max
    formula_ingredients.each do |t|
      t.use = false
      t.min = nil
      t.max = nil
      t.actual = 0
    end
  end

  def count_cost_set_weight
    amt = 0
    formula_ingredients.each do |t|
      amt = amt + (t.actual * self.batch_size * t.ingredient.cost)
      t.weight = (t.actual * self.batch_size).round(4)
    end
    @prev_cost = self.cost
    self.cost = (amt/batch_size).round 4
  end

  def put_error_to_formula
    self.formula_ingredients.each do |t|
      t.actual = -1
      t.shadow = -1
    end

    self.formula_nutrients.each do |t|
      t.actual = -1
    end
  end

  def put_soultion_to_formula solution
    solution[:formula].each do |s|
      a = s.split(",")
      ingredient_id = a[0].split('_')[1].to_i
      actual = a[1].to_d
      shadow = a[2].to_d
      formula_ingredient = self.formula_ingredients.find { |t| t.ingredient_id == ingredient_id }
      formula_ingredient.actual = actual
      formula_ingredient.shadow = shadow
    end

    solution[:specs].each do |s|
      a = s.split(",")
      nutrient_id = a[0].split('_')[1].to_i
      actual = a[1].to_d
      formula_nutrient = self.formula_nutrients.find { |t| t.nutrient_id == nutrient_id }
      formula_nutrient.actual = actual
    end
    @status = 'Optimized'
  end

  def set_actual_to_zero
    self.formula_ingredients.each { |t| t.actual = 0 }
    self.formula_nutrients.each { |t| t.actual = 0 }
  end

  def random_word
    a = ""
    rand(10).times do
      a += %w(a b c d e f g h i j k l m n o p q r s t u v w x y z)[rand(26)]
    end
    a
  end

  def floor(number, exp = 0)
    multiplier = 10 ** exp
    ((number * multiplier).floor).to_f/multiplier.to_f
  end
end

app/controllers/formulas_controller.rb
require './app/views/formulas/formula_pdf.rb'

class FormulasController < ApplicationController

  def delete_history
    fetch_formula
    @formula.delete_history params[:logged_at]
    flash[:danger] = "Formula deleted #{params[:logged_at]}"
    render :edit
  end

  def log
    fetch_formula
    if @formula
      @formula.log_to_history
      redirect_to edit_formula_path(@formula)
    else
      flash[:danger] = "Ooppps, fail to log Formula."
      redirect_to edit_formula_path(@formula)
    end
  end

  def set_history
    fetch_formula
    if @formula
      @formula.set_current_formula_ingredients_from_history params[:logged_at]
      flash.now[:success] = "Formula changed to #{params[:logged_at]}"
      render :edit
    end
  end

  def update_daily_usage
    fetch_formula
    @formula.update_attribute(:usage_per_day, params[:usage]) if @formula
  end

  def show
    fetch_formula
    respond_to do |format|
      format.pdf do
        pdf = FormulaPdf.new(@formula, view_context)
        send_data pdf.render, filename: "formula_#{@formula.name}",
                              type: "application/pdf",
                              disposition: "inline"
      end
    end
  end

  def index
    @terms = params[:search] ? params[:search][:terms] : nil
    @formulas = Formula.find_formulas(@terms).page(params[:page])
  end

  def edit
    fetch_formula
  end

  def update
    fetch_formula
    params[:commit] == 'Calculate' ? calculate : up_date
  end

  def new
    @formula = Formula.new
  end

  def create
    if params[:commit] == 'Calculate'
      calculate
    else
      kreate
    end
  end

  def destroy
    fetch_formula
    @formula.destroy
    flash[:success] = "Formula destroyed successfully."
    redirect_to formulas_path
  end

private

  def calculate
    @formula = Formula.new unless @formula
    @formula.calculate formula_params
    if @formula.status == "Optimized"
      flash[:info] = @formula.status
    else
      flash[:danger] = @formula.status
    end
    if @formula.new_record?
      render :new
    else
      render :edit
    end
  end

  def kreate
    @formula = Formula.new formula_params
    @formula.user_id = current_user.id
    if @formula.save
      flash[:success] = "Formula created successfully."
      redirect_to edit_formula_path(@formula)
    else
      flash[:danger] = "Ooppps, fail to update Formula."
      render :new
    end
  end

  def up_date
    if @formula.update(formula_params)
      flash[:success] = "Formula updated successfully."
      @premix.premix_ingredients.destroy_all
      redirect_to edit_formula_path(@formula)
    else
      flash[:danger] = "Ooppps, fail to update Formula."
      render :edit
    end
  end

  def fetch_formula
    @formula = current_user.formulas.find params[:id]
    @premix = Premix.find @formula.id
  end

  def formula_params
    params.require(:formula).
      permit(:name, :batch_size, :note, :cost, :usage_per_day,
        formula_nutrients_attributes: [:id, :_destroy, :nutrient_id, :max, :min, :actual, :use],
        formula_ingredients_attributes: [:id, :_destroy, :ingredient_id, :ingredient_cost, :max_perc, :min_perc, :actual_perc, :shadow, :weight, :use])
  end
end

app/views/formulas/_fields.html.haml
.col-sm-3
  = f.input :name, autofocus: true
.col-sm-1
  = f.input :batch_size, label: "Batch (#{current_user.weight_unit})", input_html: { type: :text }
.col-sm-1
  = f.input :cost, label: "#{current_user.weight_unit} Cost", input_html: { readOnly: true, type: :text }
.col-sm-1
  = f.input :prev_cost, label: "Previous", input_html: { readOnly: true, type: :text, class: :numeric }
.col-sm-1
  = f.input :savings, label: f.object.savings > 0 ? "Extra" : "Savings", input_html: { readOnly: true, type: :text, class: :numeric }
.col-sm-2
  = f.input :usage_per_day, label: "Daily Usage(#{current_user.weight_unit})", input_html: { type: :text, class: :numeric }
.col-sm-3
  = f.input :note, input_html: { rows: 1 }

app/views/formulas/_formula_ingredients.html.haml
.col-sm-7
  %table.table.lcf-table
    %thead
      %tr
        %th.col-sm-4= f.link_to_add 'Select Ingredients', :formula_ingredients, id: 'select_ingredients_button', class: 'btn btn-success'
        %th Cost
        %th Min %
        %th Max %
        %th Actual %
        %th Weight
        %th Shadow
    %tbody#ingredients
      = f.fields_for :formula_ingredients, f.object.formula_ingredients.sort_by { |t| -t.actual }, :wrapper => false do |builder|
        = render 'ingredients', f: builder 

app/views/formulas/_formula_nutrients.html.haml
.col-sm-5
  %table.table.lcf-table
    %thead
      %tr
        %th.col-sm-5= f.link_to_add 'Select Nutrients', :formula_nutrients, id: 'select_nutrients_button', class: 'btn btn-success'
        %th Min
        %th Max
        %th Actual
    %tbody#nutrients
      = f.fields_for :formula_nutrients, f.object.formula_nutrients.sort_by { |t| t.min ? -t.min : -t.actual }, :wrapper => false do |builder|
        = render 'nutrients', f: builder

app/views/formulas/_ingredients.html.haml
%tr.fields.ingredient{style: hide_if_destroyed(f.object)}
  = f.hidden_field :ingredient_id, class: 'ingredient_id'
  = f.hidden_field :_destroy, class: 'destroy'
  %td.col-xs-4.check-text-box
    = f.check_box :use
    = f.input_field :ingredient_name, readOnly: true, tabIndex: -1
  %td= f.input_field :ingredient_cost, type: :text, class: :numeric
  %td= f.input_field :min_perc, type: :text, class: :numeric
  %td= f.input_field :max_perc, type: :text, class: :numeric
  %td= f.input_field :actual_perc, type: :text, class: :numeric, readOnly: true, tabIndex: -1
  %td= f.input_field :weight, type: :text, class: :numeric, readOnly: true, tabIndex: -1
  %td= f.input_field :shadow_price, type: :text, class: :numeric, readOnly: true, tabIndex: -1

app/views/formulas/_nutrients.html.haml
%tr.fields.nutrient{style: hide_if_destroyed(f.object)}
  = f.hidden_field :nutrient_id, class: 'nutrient_id'
  = f.hidden_field :_destroy, class: 'destroy'
  %td.check-text-box.col-xs-5
    = f.check_box :use
    = f.input_field :nutrient_name_unit, readOnly: true, tabIndex: -1
  %td= f.input_field :min, type: :text, class: :numeric
  %td= f.input_field :max, type: :text, class: :numeric
  %td= f.input_field :actual, readOnly: true, type: :text, class: :numeric, tabIndex: -1

app/views/formulas/edit.html.haml
= render_flash
= simple_nested_form_for @formula do |f|
  %legend= "Edit Formula #{"Logged at " + params[:logged_at] if params[:logged_at]}"
  = render 'fields', f: f
  .col-sm-12
    = f.button :submit, 'Calculate', class: 'btn btn-info'
    = f.button :submit, 'Save Changes', class: 'btn btn-primary'
    = link_to 'Cancel Changes', edit_formula_path(@formula), class: 'btn btn-warning'
    = link_to 'Back to Index', formulas_path, class: 'btn btn-info'
    - if !@formula.changed?
      = link_to 'Print', formula_path(@formula, format: :pdf), target: "_blank", class: 'btn btn-info'
      = link_to 'Log', formulas_log_path(id: @formula.id), class: 'btn btn-info', method: :post
      - if Premix.find(@formula.id).premix_ingredients.count > 0
        = link_to 'Edit Premix', edit_premix_path(@formula.id), class: 'btn btn-info'
      - else
        = link_to 'Create Premix', new_premix_path(id: @formula.id), class: 'btn btn-info'
  = render 'formula_ingredients', f: f
  = render 'formula_nutrients', f: f
= render 'nutrients/select_nutrients'
= render 'ingredients/select_ingredients'
.col-sm-12
  .panel.panel-default
    .panel-heading
      %strong Formula Logged Histories
    .panel-body
      - @formula.formula_ingredients_histories.map { |t| t.logged_at }.uniq.each do |k|
        .col-sm-3{ style: "padding-bottom: 3px; padding-top: 3px;"}
          = k
          = link_to "Set", formulas_set_history_path(id: @formula.id, logged_at: k), class: 'btn btn-warning'
          = link_to "X", formulas_delete_history_path(id: @formula.id, logged_at: k), method: :delete, data: { confirm: 'Are You Sure!' }, class: 'btn btn-danger'

app/views/formulas/index.html.haml
= render_flash
= simple_form_for :search, url: formulas_path, html: { class: 'form-horizontal', method: :get } do |f|
  = content_tag :div, class: 'col-sm-5' do
    = f.input_field :terms, autofocus: true, value: @terms, placeholder: 'Search Terms...'
  = f.button :submit, 'Search', class: 'btn btn-primary'
  = link_to "New Formula", new_formula_path, class: 'btn btn-success'
  = link_to "Ingredient Usage", ingredient_usages_path, class: 'btn btn-warning'
%table.table.table-striped
  %thead
    %tr
      %th Name
      %th.right-align
        = "Batch Size(#{current_user.weight_unit})"
      %th.right-align
        = "Cost(#{current_user.weight_unit})"
      %th.right-align.col-lg-1
        = "Usage Daily(#{current_user.weight_unit})"
      %th Changed Date
      %th
  %tbody
    - @formulas.each do |f|
      %tr
        %td= link_to f.name, edit_formula_path(f.id)
        %td.numeric= number_with_precision f.batch_size, precision: 4
        %td.numeric= number_with_precision f.cost, precision: 4
        %td.form-group= text_field_tag :usage_per_day, f.usage_per_day, class: "formula_usage_per_day form-control numeric", id: "#{f.id}_usage_per_day", name: "#{f.id}_usage_per_day"
        %td= f.updated_at.in_time_zone(current_user.time_zone).to_s(:long)
        %td
          = link_to "Print", formula_path(f, format: :pdf), target: '_blank', class: 'btn btn-info'
          = link_to "Print Premix", premix_path(f, format: :pdf), target: '_blank', class: 'btn btn-info'
          = link_to "Delete", f, method: :delete, data: { confirm: 'Are You Sure!' }, class: 'btn btn-danger'
          = link_to "Copy", copy_create_path(id: f.id, klass: f.class), method: :post, class: 'btn btn-success'
= paginate @formulas, params: { search: params[:search] }, theme: 'twitter-bootstrap-3'

app/views/formulas/new.html.haml
= render_flash
= simple_nested_form_for @formula do |f|
  %legend New Formula
  = render 'fields', f: f
  .col-sm-12
    = f.button :submit, 'Calculate', class: 'btn btn-info'
    = f.button :submit, 'Save New', class: 'btn btn-primary'
    = link_to 'Back to Index', formulas_path, class: 'btn btn-info'
  = render 'formula_ingredients', f: f
  = render 'formula_nutrients', f: f
= render 'nutrients/select_nutrients' 
= render 'ingredients/select_ingredients'