config/routes.rb
Rails.application.routes.draw do
  post 'copy/create'
  post 'formulas/log'
  get 'formulas/set_history'
  delete 'formulas/delete_history'
  put 'formulas/update_daily_usage'

  root 'welcome#index'

  get    'dashboard' => 'dashboard#index'
  get    'login'   => 'welcome#index'
  delete 'logout'  => 'sessions#destroy'
  get    'signup' => 'users#new'

  resources :ingredients
  resources :formulas
  resources :premixes
  resources :nutrients
  resources :users do
    put 'lock'
    put 'activate'
  end
  resource :sessions, only: [:new, :create, :destroy]
  resources :ingredient_usages, only: [:index]

end

app/views/layouts/application.html.haml
!!! 5
%html
  %head
    %meta{:charset => "utf-8"}
    %meta{"http-equiv" => "X-UA-Compatible", :content => "IE=edge,chrome=1"}
    %meta{:name => "viewport", :content => "width=device-width, initial-scale=1, maximum-scale=1"}
    = stylesheet_link_tag 'application', :media => 'all'
    = javascript_include_tag 'application'
    %title= content_for?(:title) ? yield(:title) : "Least Cost Feed"
    %meta{:content => "", :name => "description"}
    %meta{:content => "", :name => "author"}
    = csrf_meta_tags
    = yield(:head)
  %body
    %nav.navbar.navbar-inverse.navbar-fixed-top{role: "navigation"}
      .container-fluid
        .navbar-header
          %button.navbar-toggle{ type: "button", data: { toggle: "collapse", target: "#main-navbar-collapse" } }
            %span.sr-only
              Toggle navigation
            %span.icon-bar
            %span.icon-bar
            %span.icon-bar
          = link_to "Least Cost Feed", current_user ? dashboard_path : root_path, class: 'navbar-brand', id: 'lcf-brand'
        .navbar-collapse.collapse#main-navbar-collapse
          - if current_user
            %ul.nav.navbar-nav
              %li
                = link_to 'Ingredients', ingredients_path
              %li
                = link_to 'Nutrients', nutrients_path
              %li
                = link_to 'Formulas', formulas_path
              - if current_user.is_admin
                %li
                  = link_to 'Users', users_path
          - if !logged_in?
            - if !@user
              = simple_form_for :session, url: sessions_path, html: { class: 'navbar-form navbar-right' } do |f|
                = f.input_field :username, placeholder: 'Username', class: 'form-control'
                = f.password_field :password, placeholder: 'Password', class: 'form-control'
                = f.button :submit, "Login", class: "btn btn-success"
                = link_to 'Sign Up', signup_path, class: 'btn btn-info'
          - else
            %ul.dropdown.nav.navbar-nav.navbar-right
              %li.dropdown
                %a.dropdown-toggle{href:"#", "data-toggle" => "dropdown"}
                  = current_user.name
                  %b.caret
                %ul.dropdown-menu
                  %li
                    = link_to "Edit Profile", edit_user_path(current_user)
                  %li
                    = link_to 'Logout', logout_path, method: :delete
    .container
      = yield